site_name: 阿鸣的笔记空间
site_url: https://mydomain.org/mysite
site_description: A blogging site
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/c
  features:
    - navigation.footer
  palette: 
    #Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    #Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: light mode
      primary: blue
      accent: deep orange

plugins:
  - search:
  - blog:
      enabled: true
      blog_dir: .

      archive_date_format: yyyy
      archive_url_date_format: yyyy
      post_url_format: "{slug}"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/chenaming



markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details



copyright: Copyright &copy; 2024 James Willett

